config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/contact'
  get 'home/about'
  resources :articles do
    resources :comments
  end
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 5, maximum: 30}
    validates :text, presence: true, length: {minimum: 100}

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true, length: {minimum: 5, maximum: 30}
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    http_basic_authenticate_with name: "amrit", password: "pass123", except: [:index, :show]
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def update
        @article = Article.find(params[:id])
     
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
    end


    def article_params
        params.require(:article).permit(:title,:text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "amrit", password: "pass123", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end
     
      def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
      end
      
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
  <%= form_with  model: @article, local: true do |form| %>
        
        <div class="row">

        <% if @article.errors.any? %>
              <div id="error_explanation">
                <h2>
                  <%= pluralize(@article.errors.count, "error") %> prohibited
                  this article from being saved:
                </h2>
                <ul>
                  <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
        <% end %>
      

        <div class="input-field col s12 m6">
        <i class="material-icons prefix">mode_edit</i>
         <%= form.label :title %><br>
          <%= form.text_field :title, class: "white-text" %>
        </div>
        
        <div class="input-field input-outlined col s12 m12">
         <i class="material-icons prefix">textsms</i>
         <%= form.label :text %><br>
        <%= form.text_area :text , class: "materialize-textarea white-text" %>
        </div>
 </div>
        <button class="btn waves-effect waves-light" type="submit" name="action"> 
        <%= form.submit "Post on the wall" , class: "white-text" %>
          <i class="material-icons right">send</i>
        </button>
     
    <% end %>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card blue-grey darken-2">
      <div class="card-content white-text">
        <span class="card-title">
          <h2>Edit Blog</h2>
        </span>
           
           <%= render 'form' %>
           

      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div id="articles-index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h2 class="header center white-text text-lighten-2">What's written on the wall today?</h2>
        <div class="row center">
          <h5 class="header col s12 white-text light">Let's look at today's wall of blogs!</h5>
        </div>
      
       

      </div>
    </div>
    <div class="parallax"><img src="/assets/wall_background.jpg" alt="wall background img 1"></div>
</div>

<div class="container">


<% @articles.each do |article| %>
    <div class="row">
    <div class="col s6 m4 d-flex">

    <div class="card" id="myCard">
    <div class="card-panel hoverable">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="/assets/blog1.jpg" height="250px" width="100px">
    </div>
    
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">

     <%= article.title %>

      <i class="material-icons right">more_vert</i></span>
      <p><%= link_to 'Show', article_path(article) %></p>
      <p><%= link_to 'Edit', edit_article_path(article) %></p>
    </div>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">
       
       <%= article.title %>

       <i class="material-icons right">close</i></span>
      
      <p><%= article.text %></p>

    </div>
  </div>
 </div>
   <% end %>
    
</div>


 
  
   
 

</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card blue-grey darken-2">
      <div class="card-content white-text">
        <span class="card-title">
          <h2>New Blog</h2>
        </span>
           
           <%= render 'form' %>
           

      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="card blue-grey darken-2">
      <div class="card-content white-text">
        <span class="card-title">
        <div class="row">
        <div class="col s10 m10">
          <h2><%= @article.title %></h2>
        </div>
          <div class="col s1 m1">
          <div class="row center">
         <%= link_to '<i class="material-icons">edit</i> Do it'.html_safe,  edit_article_path(@article),
               class: "btn-floating waves-effect waves-light blue" %>
        </div>
        <div class="row center">
        Edit Blog
        </div>
        </div>
        <div class="col s1 m1">
         <div class="row center">
         <%= link_to '<i class="material-icons">delete</i> Do it'.html_safe,  @article,
               method: :delete,
               class: "btn-floating waves-effect waves-light blue",
               data: { confirm: 'Are you sure you want to delete this blog?' }   %>
        </div>
        <div class="row center">
        Delete Blog
        </div>
        </div>
      
          
        
         </div>
          
        </span>
           
        <small>Created at: <%= @article.created_at%></small>
        <br/><br/>
        <big><%= @article.text %></big> 

      </div>
    </div>
  </div>
</div>

<div class="row">
 <div class="col s12 m12">
<h5>Comments:</h5>
<%= render @article.comments %>
</div>
</div>

<div class="row">
 <div class="col s12 m12">
<h5>Add a comment:</h5>
<%= render 'comments/form' %>
</div>
</div>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col s6 m6">
    <div class="card">
      <div class="card-content">
        
        <span class="card-title">
          <%= comment.body %>
         
          
           <%= link_to '<i class="material-icons">delete</i> Do it'.html_safe, [comment.article, comment],
               method: :delete,
               class: "btn-floating waves-effect waves-light red right",
               data: { confirm: 'Are you sure you want to delete this comment?' }   %>
           
         
        </span>
        <small>Added at: <%= comment.created_at %></small><br/><br/>
       
        <i class="material-icons">account_circle</i>   
        <%= comment.commenter %>
        
        <br/><br/>
        

 

 

      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
  <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
        
        
        <div class="row">

        <div class="input-field col s12 m6">
        <i class="material-icons prefix">account_circle</i>
         <%= form.label :commenter %><br>
          <%= form.text_field :commenter %>
        </div>
        
        <div class="input-field input-outlined col s8 m8">
         <i class="material-icons prefix">textsms</i>
         <%= form.label :body ,"Your Comments" %><br>
        <%= form.text_area :body , class: "materialize-textarea" %>
        </div>

        <div class="input-field input-outlined col s4 m4">
        <button class="btn waves-effect waves-light" type="submit" name="action"> 
        <%= form.submit "Add Comment" , class: "white-text" %>
          <i class="material-icons right">send</i>
        </button>
        </div>
 </div>
        
     
    <% end %>

app/views/home/about.html.erb
<div id="index-banner" class="parallax-container">
   
    <div class="parallax"><img src="/assets/about_us.jpg" alt="Unsplashed background img 1"></div>
  </div>

  


 

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Who WE Are?</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h3 class="teal-text">Join Millions of Others</h3>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/assets/background6.jpg" alt="Unsplashed background img 3"></div>
  </div>

app/views/home/contact.html.erb
<div id="index-banner" class="parallax-container">
   
    <div class="parallax"><img src="/assets/contact_us.gif" alt="Unsplashed background img 1"></div>
  </div>

  


 

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h3 class="teal-text">Join Millions of Others</h3>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/assets/contact_map.jpg" alt="Unsplashed background img 3"></div>
  </div>

app/views/home/index.html.erb
<div id="index-banner" class="parallax-container">
   
    <div class="parallax"><img src="/assets/background4.jpg" alt="Unsplashed background img 1"></div>
  </div>

  <div class="container">
    <div class="section">
 <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-darken-2">Publish here what you like!</h1>
        <div class="row center">
          <h5 class="header col s12 light">Express your views your way....</h5>
        </div>
        <div class="row center">
          <a href="/articles/new" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
        </div>
        <br><br>

      </div>
    </div>
      <!--   Icon Section   -->
      
      <div class="row">

      <!--
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      -->

      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row">
          <div class="col s12 m12" >
          <h3 class="center">Hang onto your Memories!</h3>
         </div>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/assets/background5.jpg" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h3 class="teal-text">Join Millions of Others</h3>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/assets/background6.jpg" alt="Unsplashed background img 3"></div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Writewall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <script>
 
  $( document ).ready(function(){
    $(".dropdown-trigger").dropdown();
  })
  </script>

  <div class="row">

  <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <li><a href="/articles/new">Create Blog</a></li>
      <li class="divider"></li>
      <li><a href="/articles">View Blogs</a></li>
    </ul>
    <nav>
      <div class="nav-wrapper white">
        <a href="/home/index" class="brand-logo"> <img src="/assets/logo3.png" height="70px" width="130px"> </a>
        <ul class="right hide-on-med-and-down">
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Blogs<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><a href="/home/about">About WriteWall</a></li>
          <li><a href="/home/contact">Contact Us</a></li>
          <!-- Dropdown Trigger -->
          
        </ul>
      </div>
    </nav>
     </div>
     
    <%= yield %>

    <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>
  

  </body>
</html>